config/routes.rb
Rails.application.routes.draw do
  ActiveAdmin.routes(self)
  mount Attachinary::Engine => "/attachinary"

  devise_for :users,
    controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  resources :products
  root to: 'pages#home'


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/product.rb
class Product < ApplicationRecord
  geocoded_by :address
  after_validation :geocode, if: :address_changed?

  has_attachments :photos, maximum: 4
  belongs_to :user

  validates :title, presence: true
  validates :category, presence: true
  validates :description, presence: true
  validates :price, numericality: { only_integer: true }
  validates :address, presence: true, length: { minimum: 3 }
  validates :marque, presence: true
  validates :etat, presence: true
  validates :taille, presence: true


#searchbar
  def self.search(title)
    where("name ILIKE ?", "%#{title}%")
    where("content ILIKE ?", "%#{title}%")
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  enum state:  [:client, :vendeuse]

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  devise :omniauthable, omniauth_providers: [:facebook]

  validates :email, presence: true, uniqueness: true, allow_blank: false
  validates :encrypted_password, presence: true, uniqueness: true, allow_blank: false
  validates :phone, presence: true
  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :address, presence: true

has_many :products, dependent: :destroy



def self.find_for_facebook_oauth(auth)
    user_params = auth.slice(:provider, :uid)
    user_params.merge! auth.info.slice(:email, :first_name, :last_name)
    user_params[:facebook_picture_url] = auth.info.image
    user_params[:token] = auth.credentials.token
    user_params[:token_expiry] = Time.at(auth.credentials.expires_at)
    user_params = user_params.to_h

    user = User.find_by(provider: auth.provider, uid: auth.uid)
    user ||= User.find_by(email: auth.info.email) # User did a regular sign up in the past.
    if user
      user.update(user_params)
    else
      user = User.new(user_params)
      user.password = Devise.friendly_token[0,20]  # Fake password for validation
      user.save
    end

    return user
  end



end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :authenticate_user!
  include Pundit

  # Pundit: white-list approach.
  after_action :verify_authorized, except: :index, unless: :skip_pundit?
  after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?

  # Uncomment when you *really understand* Pundit!
  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
  def user_not_authorized
    flash[:alert] = "Vous n'êtes pas authorisé à acceder à cette page"
    redirect_to(root_path)
  end

  private

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  end
  before_action :authenticate_user!
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home ]   # on est pas obligé d'être loggué pour voir la home
  skip_after_action :verify_authorized

  def home
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :index, :show]
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  def index
    @products = policy_scope(Product)
    # ?pour ordonner les produits par category    @products = Product.order(:category)

    # pour la searchbar
      if params[:search]
        @products = Product.search(params[:search]).order("created_at DESC")
      else
        @products = Product.all.order('created_at DESC')
      end
    #pour le geocoder
      @products = Product.where.not(latitude: nil, longitude: nil)
    #pour le geocoder
      @hash = Gmaps4rails.build_markers(@products) do |product, marker|
      marker.lat product.latitude
      marker.lng product.longitude
    end
  end

  def show
    @product_coordinates = { lat: @product.latitude, lng: @product.longitude }
  end

  def new
   #@user = User.find(params[:user_id])
   @product = Product.new
   authorize @product
  end

  def edit
  end

  def create
    @product = current_user.products.build(product_params)
    authorize @product
    # we need `user_id` to asssociate product with corresponding user
respond_to do |format|
    if @product.save
      format.html { redirect_to @product, notice: 'Product was successfully created.' }
      format.json { render json: @product, status: :created, location: @product }
    else
      format.html { render action: "new" }
      format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
    if @product.update(product_params)
      format.html { redirect_to @product, notice: 'Product was successfully created.' }
      format.json { render json: @product, status: :created, location: @product }
    else
      format.html { render action: "new" }
      format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @product.destroy
       respond_to do |format|
      format.html { redirect_to product_url, notice: 'Product was successfully created.' }
      format.json { render json: no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
      authorize @product
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:category, :title, :description, :address, :price, :taille, :marque, :sexe, :etat, :couleur, :matiere, photos: [])
    #Mise en forme des Fonts sur les cards
      #parameters[:category] = parameters[:category].capitalize
      #parameters[:title] = parameters[:title].upcase
      #parameters[:description] = parameters[:description].downcase
      #return parameters
    end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    user = User.find_for_facebook_oauth(request.env['omniauth.auth'])

    if user.persisted?
      sign_in_and_redirect user, event: :authentication
      set_flash_message(:notice, :success, kind: 'Facebook') if is_navigational_format?
    else
      session['devise.facebook_data'] = request.env['omniauth.auth']
      redirect_to new_user_registration_url
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Dans nos @rmoires</title>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <%= stylesheet_link_tag    'application', media: 'all' %>
  </head>

  <body>
    <%= render 'shared/flashes' %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= render "shared/navbar" %>

    <%= yield %>
    <%= cloudinary_js_config %>

    <%= javascript_include_tag "https://maps.google.com/maps/api/js?libraries=places&key=#{ENV['GOOGLE_API_BROWSER_KEY']}" %>
  <%= javascript_include_tag "https://cdn.rawgit.com/printercu/google-maps-utility-library-v3-read-only/master/markerclusterer/src/markerclusterer_compiled.js" %>
  <%= javascript_include_tag "https://cdn.rawgit.com/printercu/google-maps-utility-library-v3-read-only/master/infobox/src/infobox_packed.js" %>


     <%= javascript_include_tag 'application' %>

     <%= yield(:after_js) %>




  </body>

</html>

app/views/pages/_banner.html.erb
    <div class="banner" style="background: linear-gradient(-225deg, rgba(0,101,168,0.6) 0%, rgba(0,36,61,0.6) 50%), url('images/background.jpg');">
      <div class="banner-content">
        <h1>Dans nos @rmoires</h1>
        <p>Le vide dressing tendance chic</p>
           <%= link_to "Fouiller dans les @rmoires", products_path, class: "btn btn-primary btn-lg" %>
        </form>
      </div>
    </div>

app/views/pages/_footer.html.erb
    <div id="footer">
      <div class="container">
        <div class="row">
          <div class="col-xs-4">
            <ul class="list-inline">
              <li><a href=""><i class="fa fa-youtube"></i></a></li>
              <li><a href="https://www.instagram.com/lesarmoiresdeparis/"><i class="fa fa-instagram"></i></a></li>
              <li><a href="https://www.facebook.com/pg/lesarmoiresdeparis"><i class="fa fa-facebook"></i></a></li>
            </ul>
          </div>
          <div class="col-xs-8 text-right">
            <p>Ce site est la propriété des @ArmoiresDeParis</p>
          </div>
        </div>
      </div>
    </div>

app/views/pages/home.html.erb
  <%= render "banner" %>
    <div class="container text-center padded features">
      <div class="row">
        <div class="col-xs-12 col-sm-6 col-md-3">
          <i class="fa fa-heart-o fa-4x" aria-hidden="true"></i>
          <h4>Les armoires de Paris</h4>
          <p>Triari nullo perdiscere ille eius inquam dissentientium ut in quo disputando inquam ut quae solent tum dicas a potest cum.</p>
        </div>
        <div class="col-xs-12 col-sm-6 col-md-3">
          <i class="fa fa-shopping-bag fa-4x" aria-hidden="true"></i>
          <h4>Vendez vos vetements</h4>
          <p>Ipso faeneramur omnis liberalesque mercedis faeneramur fructus ad sic natura ad enim in sed sed exigamus enim liberalitatem propensi sed.</p>
        </div>
        <div class="col-xs-12 col-sm-6 col-md-3">
          <i class="fa fa-calendar fa-4x" aria-hidden="true"></i>
          <h4>Les Prochains évenements</h4>
          <p>Alia desiderata solet solet causa et nihil vicissimque natura maxime est ex alio id coniungendam alio quisque verum hoc iis.</p>
        </div>
        <div class="col-xs-12 col-sm-6 col-md-3">
          <i class="fa fa-bullhorn fa-4x" aria-hidden="true"></i>
          <h4>Partagez nos évenements</h4>
          <p>Feci intractato sunt sed in maxima quae utatur appareat montuosis in vetustas illae animal quam commorati in si commorati silvestribus.</p>
        </div>
      </div>
    </div>

    <div class="text-center padded" id="newsletter">
      <h1>Recevoir des informations</h1>
      <p>Laissez-nous votre e-mail</p>
      <form class="form-inline">
        <input type="email" placeholder="jeanne@gmail.com" class="form-control">
        <input type="submit" value="Recevoir" class="btn btn-primary">
      </form>
    </div>

    <div class="text-center padded" >
      <h1>Les Prochains évenements</h1>
    </div>

    <div id="map" style="width: 100%;height: 500px;"></div>

 <%= render "footer" %>

  <% content_for(:after_js) do %>
    <%= javascript_tag do %>
      $(document).ready(function() {
        var handler = Gmaps.build('Google');
        handler.buildMap({ internal: { id: 'map' } }, function() {
          markers = handler.addMarkers(<%= raw @hash.to_json %>);
          handler.bounds.extendWith(markers);
          handler.fitMapToBounds();
          if (markers.length == 0) {
            handler.getMap().setZoom(2);
          } else if (markers.length == 1) {
            handler.getMap().setZoom(14);
          }
        });
      });
    <% end %>
  <% end %>

app/views/products/_card.html.erb
<div class="card"
  style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)),
         url('http://res.cloudinary.com/dbok3xp0b/image/upload/c_pad,h_200,w_300/v1508327524/qrowdmhacqk1c4blpw2b.jpg')">
  <div class="card-category">
    <p><%= product.category %></p>
  </div>
  <div class="card-description">
    <h2><%= product.title %></h2>
    <p><%= product.description %></p>
    <p style="color:red"><%= product.price %> euros</p>
  </div>
    <img class="card-user" src="https://kitt.lewagon.com/placeholder/users/tgenaitay">
       <%= link_to "", product_path(product), class: "card-link" %>
</div>

app/views/products/_form.html.erb
  <div class="row">
    <div class="col-xs-12 col-sm-6 col-sm-offset-3">
      <%= simple_form_for @product do |f| %>
      <%= f.error_notification %>
      <%= f.input :photos, as: :attachinary %>
      <%= f.input :title %>
      <%= f.input :category %>
      <%= f.input :address %>
      <%= f.input :description %>
      <%= f.input :price %>
      <%= f.input :sexe %>
      <%= f.input :taille %>
      <%= f.input :marque %>
      <%= f.input :etat, placeholder:"neuf, bon état, occasion, usé..." %>
      <%= f.input :matiere %>
      <%= f.input :couleur %>
      <%= f.submit "Ajouter un article", class: "btn btn-primary" %>
      <% end %>
    </div>
  </div>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<div class="text-center">
  <h1 >Dans nos @rmoires</h1>
  <%= form_tag(products_path, :method => "get", id: "search-form") do %>
  <%= text_field_tag :search, params[:search], placeholder: "" %>
  <%= submit_tag "Rechercher un article" %>
  <% end %>

    <% if @product.present? %>
      <%= render @products %>
    <% else %>
      <p>Nous n'avons pas ce produit <%= params[:search] %></p>
    <% end %>
</div>
  <div class="container">
    <div class="cards-container">
      <% @products.each do |product| %>
      <div class="col-xs-12 col-sm-4">
          <%= render "card", product: product %>
      </div>
      <% end %>
    </div>
    <div class="map-container">
      <div id="map"></div>
    </div>
  </div>

  <% content_for(:after_js) do %>
    <%= javascript_tag do %>
      $(document).ready(function() {
        var handler = Gmaps.build('Google');
        handler.buildMap({ internal: { id: 'map' } }, function() {
          markers = handler.addMarkers(<%= raw @hash.to_json %>);
          handler.bounds.extendWith(markers);
          handler.fitMapToBounds();
          if (markers.length == 0) {
            handler.getMap().setZoom(2);
          } else if (markers.length == 1) {
            handler.getMap().setZoom(14);
          }
        });
      });
    <% end %>
  <% end %>

app/views/products/new.html.erb
<h1 class= "text-center">Ajouter un article</h1>

<%= render 'form', product: @product %>

app/views/products/show.html.erb
    <div class="container">
      <div class="profile text-center">
        <div class="main">
          <div class="main-content">
            <img src="images/seb.jpeg" alt="" width="150" class="img-circle">
        <p>Marque: <%= @product.marque %></p>
        <p>Adresse: <%= @product.address %></p>
        <p>Matière: <%= @product.matiere %></p>

        <%= link_to 'Acheter', products_path, class:"btn btn-primary" %>
          </div>
        </div>
        <div class="stat">
          <div class="stat-content">
            <p>prix</p>
            <h3><strong><%= @product.price %>euros </strong></h3>
          </div>
        </div>
        <div class="stat">
          <div class="stat-content">
            <p>Taille: <%= @product.taille %></p>
            <p>Etat: <%= @product.etat %></p>
            <p>Couleur: <%= @product.couleur %></p>
          </div>
          </div>
        <div class="stat">
          <div class="stat-content">
          <% if policy(Product).edit? %>
              <%= link_to 'Editer', edit_product_path(@product), class:"btn btn-primary btn-xs" %>
          <%= new_product_path %>
          <% end %>
          <% if policy(Product).destroy? %>
              <%= link_to 'Supprimer', @product, method: :delete, data: { confirm: 'Etes-vous sûr de vouloir supprimer cet article' }, class:"btn btn-primary btn-xs" %>
          <% end %>
              <%= link_to 'Retour', products_path, class:"btn btn-primary btn-xs" %>
          </div>
          </div>
        <div class="description">
          <div class="description-content">
            <p>Description: </p>
            <p class="text-justify">
              <p><%= @product.description %></p>
            </p>
          </div>
        </div>
      </div>
    </div>

    <!-- code pour afficher toutes les photos
          <div class="photo1">
        <% @product.photos.each do |photo| %>
        <%= cl_image_tag photo.path, width: 100, height: 100, crop: :fill %>
        <% end %>
      </div>
--!>

app/views/shared/_avatar.html.erb
<img src='https://avatars1.githubusercontent.com/u/26875527?v=4' class="avatar"/>
<img src='https://avatars1.githubusercontent.com/u/26875527?v=4' class="avatar-large"/>

app/views/shared/_flashes.html.erb
<!-- app/views/shared/_flashes.html.erb -->
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon">
  <!-- Logo -->
  <%= link_to root_path, class: "navbar-wagon-brand" do %>
    <%= image_tag "armoires.png" %>

  <% end %>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">

    <% if user_signed_in? %>

      <!-- Links when logged in -->
    <%= link_to "Visiter le fond des @rmoires", products_path, class: "navbar-wagon-item navbar-wagon-link" %>
    <%= link_to "Les prochains evenements", "#", class: "navbar-wagon-item navbar-wagon-link" %>
    <%= link_to "Ajouter un article", new_product_path, class: "btn btn-danger" %>


      <!-- Avatar with dropdown menu -->
      <div class="navbar-wagon-item">
        <div class="dropdown">

    <% avatar_url = current_user.facebook_picture_url || "http://placehold.it/30x30" %>
    <%= image_tag avatar_url, class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>

          <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
            <li>
              <%= link_to "#" do %>
                <i class="fa fa-user"></i> <%= t(".profile", default: "Profile") %>
              <% end %>
            </li>
            <li>
              <%= link_to "#" do %>
                <i class="fa fa-home"></i>  <%= t(".profile", default: "Home") %>
              <% end %>
            </li>
            <li>
              <%= link_to destroy_user_session_path, method: :delete do %>
                <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>
              <% end %>
            </li>
          </ul>
        </div>
      </div>
    <% else %>
      <!-- Login link (when logged out) -->

 <%= link_to "Sign in with facebook", omniauth_authorize_path('user', 'facebook'), class: "navbar-wagon-item navbar-wagon-link" %><br />

      <%= link_to t(".sign_in", default: "Login"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %>
    <% end %>
  </div>

  <!-- Dropdown list appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li><a href="#">Some mobile link</a></li>
        <li><a href="#">Other one</a></li>
        <li><a href="#">Other one</a></li>
      </ul>
    </div>
  </div>
</div>